### ISSUE TITLE
Feature Request - Export to Tiled JSON Format

### ISSUE THREAD

**Issue by Silver-Streak** [deepnight/led#101] opened 2020-09-25 23:48 UTC
Hello,

 I was super excited to see LEd's releases, and after using it for a bit, I love the interface and it's autotiling system. It has all of the benefits of other editors (including embedded ones like Unity 2D) without a lot of the overhead.

While looking at the JSON export format, it makes a lot of sense to me, but it seems like it wouldn't be 1:1 compatible with most existing game engines today. They all use the format utilized by Tiled and a few other tilemappers. 

Would there be any chance of a "Tiled JSON format" export? Not asking for importing of TMX/TSX files or anything, just allowing users to export using this format so it could be imported into engines: https://doc.mapeditor.org/en/stable/reference/json-map-format/

**Comment by deepnight** [comment] 2020-09-26 11:42
That's a great suggestion :) I'll see if I can easily output a TMX file

**Comment by Silver-Streak** [comment] 2020-09-28 02:52
> That's a great suggestion :) I'll see if I can easily output a TMX file

That is awesome. Thanks for considering this! You just made a ton of people in the GDevelop game engine project very happy. 😄  

(Also, they're now potentially looking at LEd as an integrated tilemap editor in the future, but it'll require the Tiled JSON format first in order for the engine to be able to render the created tilemaps)

**Comment by RPGillespie6** [comment] 2020-09-28 03:54
Note that Tiled also has a JSON format, might be easier to just output in Tiled JSON format

**Comment by deepnight** [comment] 2020-09-28 07:51
I don't know which one is more spread out so far? JSON or TMX?

**Comment by RPGillespie6** [comment] 2020-09-28 13:28
I would guess TMX is more common because that's the default, but (IMO) it shouldn't really matter too much which Tiled format is supported by LEd, because if you export to one, Tiled itself can read it in and export to any of the others. Hence why I was saying to pick the easiest Tiled format to export to (JSON).

I think a separate CLI tool like `led2tiled.py` or `led2tiled.js` that that can perform the conversions from the command line would also be acceptable (at least in my case).

**Comment by Silver-Streak** [comment] 2020-09-28 13:49
Did some digging for you.
It seems like *most* engines support TMX/TSX over the JSON directly, but there are a lot that support the JSON as well.

- Unity has a few different addons for it, but most seem to support both JSON and TMX: https://seanba.com/supertiled2unity.html
- GDevelop (engine I use) is adapting [Pixi-Tilemap](https://github.com/pixijs/pixi-tilemap), which it looks like uses TMX and TSX (Map/tileset), although they are interested in the tiled JSON specifically for compatibility with LEd for this future feature after I mentioned it: 
    - https://github.com/4ian/GDevelop/pull/1901 
    - https://github.com/4ian/GDevelop/issues/2002
- Godot supports tmx and tsx and json: https://godotengine.org/asset-library/asset/158
- Game Maker Studio has some free asset loaders that appear to use TMX/TSX: https://marketplace.yoyogames.com/assets/8547/gmtiled2
- Phaser supports Tiled JSON: https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.Tilemap.html
- Defold has it's own JSON format, but it looks like there are a ton of Tiled JSON to Defold importers out there.
- Heaps.io supports TMX: https://heaps.io/documentation/resource-management.html

**Comment by hoxu** [comment] 2020-09-28 14:53
> I think a separate CLI tool like `led2tiled.py` or `led2tiled.js` that that can perform the conversions from the command line would also be acceptable (at least in my case) because I can just integrate the CLI invocation into my build.

A headless CLI for conversion would be nice from build pipeline point of view.

**Comment by blurymind** [comment] 2020-09-29 08:21
> That's a great suggestion :) I'll see if I can easily output a TMX file

Hi, for the purpose of using it in gdevelop, we need it to output a json file, not tmx

**Comment by blurymind** [comment] 2020-09-29 17:09
Here is a spec of tiled's JSON format
https://doc.mapeditor.org/en/stable/reference/json-map-format/

I hope it's helpful for writing an exporter.

My only concern is in getting extra data that led exports to the right places of tiled (custom game entities and their properties). I believe tiled also exports that sort of data, so it should not be hard.

Also worth noting that tiled's exported json contains data about both the tilemap and the tileset. A tilemap can also have more than one tilesets. I havent properly looked at led's json export data, but I would imagine it is also exporting this stuff.

In any case this should help migrate a lot of people from tiled to led. If they can migrate their maps, they might migrate their existing games to led

**Comment by deepnight** [comment] 2020-09-30 14:40
I've made some cleaning to prepare for a **TMX exporter**. You can now read an auto-generated doc of the JSON format here: https://github.com/deepnight/led/blob/master/JSON_DOC.md

**Comment by deepnight** [comment] 2020-10-01 14:39
It's coming along nicely :) 

![tiled](https://user-images.githubusercontent.com/1671695/94823822-96201f80-0404-11eb-8bba-2d3864e7a6bc.png)

**Comment by blurymind** [comment] 2020-10-01 15:18
if this reads and writes to tiled format json format, we might be able to bundle it with gdevelop and use it as the default tilemap editor.

**Comment by blurymind** [comment] 2020-10-01 17:45
I see. In that case it might be easier for me to implement an led json parser for gdevelop, since for xml type documents we would need a new dependency to parse them into objects. Unless anyone knows a good way to parse xml without jquery? :)

**Comment by RPGillespie6** [comment] 2020-10-01 18:14
> I see. In that case it might be easier for me to implement an led json parser for gdevelop, since for xml type documents we would need a new dependency to parse them into objects. Unless anyone knows a good way to parse xml without jquery? :)

It's not will documented, but you can use Tiled from the CLI as well. So for example you could do:

```
tiled.exe map.tmx --export-map map.json
```

And it would convert from tmx to Tiled json.

**Comment by blurymind** [comment] 2020-10-01 23:46
The idea is to allow gdevelop users directly edit their tile maps inside
gdevelop by spawning an instance of led. Since led runs in electron and
gdevelops ide runs in electron, you can bundle the two in one ide
potentially. Tiled is an executable binary and adding its size to the
deployment size just to convert a file to Json would be wasteful and
pointless. Might as well use tiled instead if we are gonna do that.

The html5 nature of led is what makes it a better candidate for this and it
is a much better fit to either parse its data properly or parse data that
it exports, no Middleware should be involved in between. You click on a
tile map in gdevelop and led pops up to let you edit it, or even better its
inside the gdevelop ide as a new tab.

**Comment by deepnight** [comment] 2020-10-02 07:51
I see the idea :) 

The best approach would definitely to write a simple LEd JSON parser, rather than relying on Tiled for that, because of all Tiled limitations (the conversion from LEd to Tiled isn't _lossless_).

I can also add support for extra app parameters to start the editor on a specified map directly, for example.

**Comment by blurymind** [comment] 2020-10-02 08:06
> I see the idea :)
> 
> The best approach would definitely to write a simple LEd JSON parser, rather than relying on Tiled for that, because of all Tiled limitations (the conversion from LEd to Tiled isn't _lossless_).
> 
Yes the more I look into it, the more it makes sense to parse Led's json format sepparately from our tiled json parsing.

> I can also add support for extra app parameters to start the editor on a specified map directly, for example.
Yes please, that will help a lot for integrating it. We need a way to initiate it with a map by passing the json parsed object or a path to the json file it. We need a way to initiate it with a new document with a specified name and a way to tell it to save its document.

You can see how we have done it for the currently bundled external editors
https://github.com/4ian/GDevelop/tree/master/newIDE/app/public/external

The xxx-main.js file is what is bridging the external editor and gdevelop. For example piskel's
https://github.com/4ian/GDevelop/blob/master/newIDE/app/public/external/piskel/piskel-main.js

We wait for piskel to load (load callback would be helpful too), then we tell it to either open a file that gdevelop sent it or start a new one. We also add a custom header for saving the file or changing the path to save it to.
This only works in the electron version of gdevelop atm - spawning the editor as a modal window.

My hope is that one day we will embed external editors as tabs inside the IDE's react interface instead

**Comment by deepnight** [comment] 2020-10-02 09:26
Ok let's continue GDevelop related questions in #126 :)

**Comment by deepnight** [comment] 2020-11-02 16:24
Close as duplicate of #177

**Closed by deepnight** 2020-11-02 16:24 UTC
Labels: new feature

**Comment by airtonix** [comment] 2022-03-28 21:31
> My hope is that one day we will embed external editors as tabs inside the IDE's react interface instead

lol.
