### ISSUE TITLE
Building/running  on macOS

### ISSUE THREAD

**Issue by virtualritz** [deepnight/led#104] opened 2020-09-26 18:02 UTC
When I do this step:
```
haxe renderer.debug.hxml
````
I get:
```
Error: Error: Cannot process [castle]: Library castle is not installed : run 'haxelib install castle'
```

Doing an:
```
haxelib install castle
```
makes the build go through.

If this is needed for all platforms, it should probably be added to the README.

When I try to run it, I get:
```
npm run start

> led@0.2.1-beta start /Users/moritz/code/led/app
> electron .

Checking for update
Error: Error: ENOENT: no such file or directory, open '/Users/moritz/code/led/app/dev-app-update.yml'
(node:4196) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/moritz/code/led/app/dev-app-update.yml'
(node:4196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And it just hangs. Electron is open but I never see a window.

**Comment by deepnight** [comment] 2020-09-26 19:36
Yes the first one is an old dependency that I should get rid of (not sure about CastleDB support for now, looking for alternatives, see #20 )

The error you see shouldn't block the execution as far as I know, I have the same output as you on my electron "main" window 🤔

Do you see a dark blue window opened somewhere? If so, could you please check the dev console (should be CMD+SHIFT+I shortcut, or "Debug tools" menu if it can be seen anywhere?

**Comment by virtualritz** [comment] 2020-09-26 20:20
> The error you see shouldn't block the execution as far as I know, I have the same output as you on my electron "main" window 🤔

Correct, Electron is running but nothing is happening.
> Do you see a dark blue window opened somewhere? If so, could you please check the dev console (should be CMD+SHIFT+I shortcut, or "Debug tools" menu if it can be seen anywhere?

No window. And what's more: while I was writing this answer, I had the Electron that `npm` launched open (just the menu bar). My mouse froze and my mac rebooted.
Now, after the reboot, when I do `npm run start` the terminal looks the same but I get no Electron icon in my tasks any more (and no menu bar). Could be that macOS quarantined the app because it caused the reboot?
Before the reboot though, even using the Electron menu doing a View->Toggle Developer Tools (or pressing `Cmd`+`Option`+`I` ) did nothing.

When I launch Electron directly I get the blue window and can open the developer tools.

**Comment by deepnight** [comment] 2020-09-26 21:17
Woah. That's super weird! Could you please try deleting the `node_modules` folder from `app/`? 

You can then run again:
```
npm i
```

Do you get the same following result by running this command?
```
npm list --depth=0
```

Expected:
```
led@0.2.1-beta C:\projects\led\app
+-- electron@10.1.0
+-- electron-builder@22.8.0
+-- electron-updater@4.3.4
`-- sortablejs@1.10.2
```

**Comment by virtualritz** [comment] 2020-09-26 22:04
> ```
> npm i
> ```
Did that. Same as before (and no app icon/no way to switch to the app). But the task is there.
I see 4 tasks, actually:
```
Electron
Electron Helper
Electron Helper (GPU)
Electron Helper (Renderer)
```
> Do you get the same following result by running this command?
> 
> ```
> npm list --depth=0
> ```
> 
> Expected:
> 
> ```
> led@0.2.1-beta C:\projects\led\app
> +-- electron@10.1.0
> +-- electron-builder@22.8.0
> +-- electron-updater@4.3.4
> `-- sortablejs@1.10.2
> ```

I get this:
```
led@0.2.1-beta /Users/moritz/code/led/app
├── electron@10.1.2
├── electron-builder@22.8.1
├── electron-updater@4.3.5
└── sortablejs@1.12.0
```

And here is the complete log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/14.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle led@0.2.1-beta~prestart: led@0.2.1-beta
6 info lifecycle led@0.2.1-beta~start: led@0.2.1-beta
7 verbose lifecycle led@0.2.1-beta~start: unsafe-perm in lifecycle true
8 verbose lifecycle led@0.2.1-beta~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/moritz/code/led/app/node_modules/.bin:/usr/local/var/pyenv/shims:/usr/local/var/pyenv/shims:/usr/local/opt/qt/bin:/usr/local/var/pyenv/shims:/Applications/Inkscape.app/Contents/MacOS:/usr/local/opt/sphinx-doc/bin:/Users/moritz//Library/Python/3.7/bin:/usr/local/opt/android-sdk/build-tools/19.1.0:/usr/local/opt/android-sdk/platform-tools:/usr/local/opt/android-sdk/tools:/usr/local/opt/gradle/bin:/usr/local/opt/maven/bin:/usr/local/opt/ant/bin:/Users/moritz/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/3Delight/bin:/opt/local/bin:/opt/local/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/Applications/3Delight/bin:/Users/moritz/Tools/flutter/bin:/Users/moritz/Library/Android/sdk/platform-tools/:/usr/local/sbin
9 verbose lifecycle led@0.2.1-beta~start: CWD: /Users/moritz/code/led/app
10 silly lifecycle led@0.2.1-beta~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle led@0.2.1-beta~start: Returned: code: 1  signal: null
12 info lifecycle led@0.2.1-beta~start: Failed to exec start script
13 verbose stack Error: led@0.2.1-beta start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid led@0.2.1-beta
15 verbose cwd /Users/moritz/code/led/app
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/Cellar/node/14.11.0/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v14.11.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error led@0.2.1-beta start: `electron .`
22 error Exit status 1
23 error Failed at the led@0.2.1-beta start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sangohan** [comment] 2020-09-27 08:23
I've found that the line https://github.com/deepnight/led/blob/cdcdd317af62fcbfdb80609a419fb6b396df0058/src.main/ElectronMain.hx#L16 is the cause - setting the `show` option to `true` allows me to start the electron editor on osx.

**Comment by virtualritz** [comment] 2020-09-27 09:47
Confirmed. I only tested setting `show` to `true` and that works for me.

Albeit only after deleting and cloning the repo again. I think something inside that repo got quarantined so well by macOS, when my machine crashed, that Electron would simply not start any more at all from there (not even windowless).

**Comment by virtualritz** [comment] 2020-09-27 10:12
Ok, so here are the issues I encounter after running:

1. The editor always opens on the same screen. I have a 4k monitor connected to my laptop. Electron always opens as a fullscreen window on the laptop's 2.7k screen. Even if I had it as a smaller window on the 4k monitor before closing it.
2. When I move the window over to the monitor it slides *under* the terminal from which I launched the app.I have never seen this before/knew this was possible. 
3. I do not see the Electron menu bar at the top. The menu bar is that of the terminal. 
4. This is super weird: basically the app under/behind the L-Ed window that covers the portion of the screen the mouse is over receives any keyboard command.
I.e. I have usually three columns of windows: terminal, editor, browser. Now L-Ed is on top. If I press `Cmd`+`+` to zoom while over the left side of L-Ed, my terminal, behind, changes font size, middle the same happens to my editor, right side browser.

**Comment by ConnorBP** [comment] 2020-09-27 21:38
Used your fix for this bug building this for my own machine. Added your fix posted here to a PR while I was at it. Would appreciate if someone could double check that this does not break anything on windows.

**Comment by deepnight** [comment] 2020-09-28 12:16
Thanks for the PR 👍 

About the multi-monitor problem, I'll add an issue and test a little bit more asap.

**Closed** 2020-09-28 12:18 UTC
Labels: bug, help wanted, need more infos
