### ISSUE TITLE
"Export Tiled TMX" is in the wrong format

### ISSUE THREAD

**Issue by kaiiboraka** [deepnight/led#166] opened 2020-10-14 00:08 UTC
![image](https://user-images.githubusercontent.com/7596816/95928235-17b96b00-0d7e-11eb-999c-1ec88eb1a995.png)

Hello, I'm not sure if this design is intentional or not, but the .tmx that LEd creates turns every tile into a separate object within Tiled, which is counter to how one would think it should work.

![image](https://user-images.githubusercontent.com/7596816/95928374-6ff06d00-0d7e-11eb-8928-e2fbc1c47eb4.png)

Currently when I open the .tmx generated by LEd, I have an Object Layer with all of the Tiles, instead of a Tile Layer with the tiles. This significantly hampers workflow within Tiled but also (as in my case) within Unity. I'm using a package called SuperTiled2Unity, which takes the data of a .tmx file and turns it into a Unity Prefab that's very simplistically drag-and-drop. However as is, I'm getting hundreds of separate game objects in my scene because the LEd tiles are turning into Tiled Objects instead of Tiled Tiles, which all exist together on one Grid layer instead of being separate as objects are.

I propose that saving to TMX should consider the Layer type within LEd to determine whether or not exported things should be Objects or Tiles. IntGrids, for example, should be Tiles. Entities and the content of Enums, however, would be objects.

**Comment by deepnight** [comment] 2020-10-14 08:31
As explained in the doc, Tiled doesn't support freely positioned tiles, and therefore, doesn't support tiles created by rules that don't align with the grid. 

I don't think it's possible to export "tiles snapped on the grid" as proper "Tiled tile layer", and "tiles not on the grid" as "Tiled objects", because the render order won't be correct with overlapping tiles.

**Comment by deepnight** [comment] 2020-10-14 08:32
It will become even more incompatible as soon as the "free tile positioning" feature will be available (see #32 )

**Comment by kaiiboraka** [comment] 2020-10-14 16:58
I see. So I went to the Tiled Discord to try and see if they had a solution to my particular use-case on their end, and I actually wound up with an interesting response from the main dev himself.

![image](https://user-images.githubusercontent.com/7596816/96020617-885a9900-0e0b-11eb-9829-09f3989ef0aa.png)

It seems to me like there's mostly just a misunderstanding going on here in how either program "actually works." It seems like there are potential solutions to be found here, and I wouldn't mind perhaps taking a crack at helping come up with the middle-ground solution that would take into account Tiled's structure for use with LEd's export. 

If for no other reason than for the sake of my own desired workflow! Hahah

**Comment by deepnight** [comment] 2020-10-14 19:36
There's definitely some misunderstanding here, as Tiled author thought I was bashing Tiled here whereas I'm only stating incompatibility issues (and all of them are still true & exists):

 - Different grid sizes isn't a rare use case if this feature is available. I don't plan to do some broken export that works for plugins but don't work for the actual Tiled app :) It's either a supported feature or not.
 - Stacked tiles per layers are a requirement because of auto-layer rule system: you can have some transparent grass tile, over a dirt ground, over a background wall. I could create 1 layer per stack level, but this would lead to a weird TMX output with tons of "fake" layers to emulate this feature.
 - Freely positioned tiles are on LEd roadmap and when this feature will be available, it will make "classic Tiled tile layers" even less compatible. That's a good reason for not using them for just a few weeks.

And no, IntGrid can't be emulated in Tiled. I actually started doing it as he describes, but Tiled "GID" system breaks IntGrid values. For example, the value 0, 1 and 2 in LEd will become, say, 217, 218 and 219 if the "fake tileset" proposal has a GID starting at 217.

I agree on one point: it's not great when open source projects authors don't cooperate :) 

On my side, I tried to connect to Tiled, spending some of my time to offer a "Tiled option" that exports LEd data with the highest possible fidelity to TMX files. But I can't pretend incompatibilities don't exist.

**Comment by bjorn** [comment] 2020-10-20 08:45
Thanks for explaining the incompatibilities in more detail @deepnight! Also thanks for visiting the Tiled Discord to help clear up the confusion, and my apoligies for the misunderstanding on my part!

I agree on all accounts. It still might be preferable to export tile layers and issue a warning when an unsupported feature is used (like multiple tiles in the same location on the same layer, or tiles that are not aligned to the grid), rather than exporting everything as objects which at least in @kaiiboraka case is not helpful. On the other hand, I understand the "tile objects" export is very much in line with the native JSON format used by LEd.

> And no, IntGrid can't be emulated in Tiled. I actually started doing it as he describes, but Tiled "GID" system breaks IntGrid values. For example, the value 0, 1 and 2 in LEd will become, say, 217, 218 and 219 if the "fake tileset" proposal has a GID starting at 217.

Just to clear this up, the GID starting at 217 is just because multiple tilesets are mapped into the same ID range in the TMX map format. It does not mean IntGrid can't be emulated in Tiled, since the values 0, 1, 2 will still be 0, 1 and 2 in terms of the local tile IDs within the IntGrid's "tileset", which is what matters in the end.

In any case, I'm looking forward to see where you'll take LEd!

**Comment by deepnight** [comment] 2020-10-20 09:06
Thanks for your help! I added a specific issue for 0.5.0 milestone, this will need some testing :)

**Comment by deepnight** [comment] 2020-11-02 16:18
In 0.5.0, LEd tiles will be exported to proper Tiled tile layers. 

However, because of the LEd support for tile stacking, some additional Tiled layers will be generated in the process.

**Comment by deepnight** [comment] 2020-11-02 16:19
Close as duplicate of #177

**Closed by deepnight** 2020-11-02 16:19 UTC
Labels: enhancement, need more infos
